### PR TITLE
request body empty

### PR DESCRIPTION
**Pull request by govind-maheshwari2**
If Request doen't have body but response is going to be msgpack encoded. in that case body.text empty check is req. and return if body is empty

### CODE REVIEW

**Comment by dinkopehar** [comment]
Hi @govind-maheshwari2 Thank you for taking time to look into this project.

I'm not sure I understand the problematic here. When plugin is enabled, what happens if **body is empty** ? Assuming the endpoint you are sending request to doesn't look into body and returns msgpack response, plugin will automatically decode it.
What is the purpose having `return` early if body is empty ?

**Comment by govind-maheshwari2** [comment]
Hi @dinkopehar 
This issue is if we send a request with an empty body with the plugin enabled then it will give an error as it is trying to encode an empty string.
As the code fails at encoding only it will throw an error then the request will not be sent by insomnia.
You can repro this by sending no body or empty body to any request.

**Comment by dinkopehar** [comment]
Oh, I didn't checked all exceptions.

When I tested, I assumed the body of request and response would not be empty. I didn't checked for cases you mention. There is also similar issue open.

I'll approve these changes, thank you :rocket:

**Comment by govind-maheshwari2** [comment]
Hi @dinkopehar 
Any plans regarding deploying the plugin with this change?

**Comment by dinkopehar** [comment]
Hi @govind-maheshwari2 

I just republished the package and tested by installing it. You can also delete the previous version of plugin or update existing one to 0.0.4

**Pull request merged**
